CREATE TABLE `projects` (
  `project_reference` varchar(255) NOT NULL,
  `datacenter_reference` text,
  `project_name` text,
  `project_abstract` text,
  `project_citation` text,
  `project_pi` text,
  `project_pi_organization` text,
  `project_pi_contact` text,
  `project_geospatial_lon_min` double DEFAULT NULL,
  `project_geospatial_lon_max` double DEFAULT NULL,
  `project_geospatial_lat_min` double DEFAULT NULL,
  `project_geospatial_lat_max` double DEFAULT NULL,
  `geospatial_vertical_min` text,
  `geospatial_vertical_max` text,
  PRIMARY KEY (`project_reference`)
);

CREATE TABLE `animals` (
  `animal_project_reference` varchar(255) DEFAULT NULL,
  `datacenter_reference` text,
  `animal_reference_id` varchar(255) NOT NULL DEFAULT '',
  `animal_guid` text,
  `vernacularname` text,
  `scientificname` text,
  `taxonrank` text,
  `aphiaid` double DEFAULT NULL,
  `tsn` double DEFAULT NULL,
  `animal_origin` text,
  `stock` text,
  `length` double DEFAULT NULL,
  `length_type` text,
  `weight` double DEFAULT NULL,
  `life_stage` text,
  `age` text,
  `sex` text,
  PRIMARY KEY (`animal_reference_id`),
  KEY `fk_animal_project` (`animal_project_reference`),
  CONSTRAINT `fk_animal_project` FOREIGN KEY (`animal_project_reference`) REFERENCES `projects` (`project_reference`)
);

CREATE TABLE `detections` (
  `detection_project_reference` varchar(255) DEFAULT '',
  `datacenter_reference` varchar(255) DEFAULT '',
  `detection_id` varchar(255) NOT NULL DEFAULT '',
  `detection_guid` text,
  `time` datetime DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `tracker_reference` text,
  `detection_reference_id` varchar(255) DEFAULT '',
  `detection_reference_type` text,
  `transmitter_codespace` text,
  `transmitter_id` double DEFAULT NULL,
  `detection_transmittername` text,
  `detection_serial_number` double DEFAULT NULL,
  `sensor_data` text,
  `sensor_data_units` text,
  `receiver_log_id` text,
  `deployment_id` text,
  PRIMARY KEY (`detection_id`),
  KEY `fk_detection_project` (`detection_project_reference`),
  KEY `fk_detection_animal` (`detection_reference_id`),
  CONSTRAINT `fk_detection_animal` FOREIGN KEY (`detection_reference_id`) REFERENCES `animals` (`animal_reference_id`),
  CONSTRAINT `fk_detection_project` FOREIGN KEY (`detection_project_reference`) REFERENCES `projects` (`project_reference`)
);

CREATE TABLE `platforms` (
  `platform_project_reference` varchar(255) DEFAULT NULL,
  `datacenter_reference` text,
  `platform_reference_id` text CHARACTER SET utf8 COLLATE utf8_bin,
  `platform_guid` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `platform_type` text,
  `platform_depth` double DEFAULT NULL,
  `platform_name` text CHARACTER SET utf8 COLLATE utf8_bin,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  PRIMARY KEY (`platform_guid`),
  KEY `fk_platform_project` (`platform_project_reference`),
  CONSTRAINT `fk_platform_project` FOREIGN KEY (`platform_project_reference`) REFERENCES `projects` (`project_reference`)
);

CREATE TABLE `releases` (
  `release_project_reference` varchar(255) DEFAULT '',
  `datacenter_reference` text,
  `tag_device_id` text,
  `release_guid` varchar(255) NOT NULL DEFAULT '',
  `release_reference_id` varchar(255) DEFAULT '',
  `release_reference_type` text,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `time` datetime DEFAULT NULL,
  `expected_enddate` text,
  `manufacturer` text,
  `tag_model` text,
  `tag_serial_number` int(11) DEFAULT NULL,
  `tag_coding_system` text,
  `transmitted_id` double DEFAULT NULL,
  `transmittername` text,
  PRIMARY KEY (`release_guid`),
  KEY `fk_release_project` (`release_project_reference`),
  KEY `fk_release_animal` (`release_reference_id`),
  CONSTRAINT `fk_release_animal` FOREIGN KEY (`release_reference_id`) REFERENCES `animals` (`animal_reference_id`),
  CONSTRAINT `fk_release_project` FOREIGN KEY (`release_project_reference`) REFERENCES `projects` (`project_reference`)
);
